spring:
  application:
    name: account-service-server

    # ------------- DataBases
  datasource:
    url: jdbc:postgresql://localhost:5436/account_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  output:
    ansi:
      enabled: always

#  liquibase:
#    change-log: classpath:/db/changelog/master.yaml

logging:
  level:
    root: info
  #    org:
  #      springframework:
  #        security: debug

  file:
    name: logs/spring.log

queue:
  name: firstQueue
  request:
    name: get-amount-request-queue
  response:
    name: get-amount-response-queue

server:
  port: 8072
